### PR TITLE
Add a space between the URL and the surrounding parens

### PR DESCRIPTION
**Pull request by JesseWeinstein**
to make various auto-linkers happy

### CODE REVIEW

**Comment by yipdw** [comment]
Hmm, interesting.  Which auto-linker doesn't handle `(URL)`?

Can we use `<URL>` instead? `<` and `>` must be percent-encoded to appear in a URL (whereas `(` and `)` don't have to be); maybe that'll help things.

**Comment by JesseWeinstein** [comment]
I noticed it in Pidgin, as distributed with Debian Wheezy. And it only works if it's a close paren *followed* by a colon. < > seems to work, even with the colon. So we could change over to that, rather than adding the space, if you'd prefer.

**Comment by yipdw** [comment]
Yeah, I think I'd prefer < >.  It's a small difference, but `<URL>` just looks better to me than `( URL )`.

**Comment by chronomex** [comment]
I second <>. Some Wikipedia URLs have unescaped parens, for example.

**Comment by JesseWeinstein** [comment]
OK, PR updated to use < >.

**Pull request merged**
