### PR TITLE
Global ignore: Add facebook.com/widgets/

### PR DESCRIPTION
**Pull request by C4K3**

### CODE REVIEW

**Comment by JustAnotherArchivist** [comment]
Hmm. The widgets are what's embedded in sites to have the like button, right? I'd say we should keep grabbing those. See also #197, in particular @yipdw's comment there.

**Comment by yipdw** [comment]
Yeah, putting these into their own ignore set makes the most sense to me.

**Comment by JustAnotherArchivist** [comment]
> Especially in cases where a website is due to shutdown soon, it would be bad to spend time grabbing stuff like this over the actual content.

Right, this is something I'm trying to address by implementing URL priorisation into wpull and ArchiveBot. This will (among other things) allow deferring external content to the end of the job. Hopefully, I can resume working on that soon.

**Comment by JustAnotherArchivist** [comment]
Per discussion above, this should be a separate igset, so I'm closing this PR.

NB, while there are many other similar examples of buttons embedded in pages that we should probably normally grab but might occasionally want to ignore, Facebook is by far the worst one because it pulls in thousands of JS URLs.

**Pull request closed without merging**
