### PR TITLE
viewer: Add JSON interface to search endpoint

### PR DESCRIPTION
**Pull request by yipdw**
This eases programmatic access to the viewer's database, e.g.

    curl -s 'http://HOST/index.json?q=tumblr' | jq '[.results[].domain]'

### CODE REVIEW

**Comment by yipdw** [comment]
Paging @chfoo, @ivan, and anyone else who is likely to know of the best way to implement these sorts of things in Tornado's Web framework.

I'm not attached to the endpoint name; I'd prefer something like `/archivebot/viewer.json?q=...` or `/archivebot/viewer/archives.json?q=...` but that's bias from years of Rails.

**Comment by chfoo** [comment]
Looks ok to me. Doing it the best way would probably require another framework on top of Tornado.

I personally like putting everything under `/api/` such as `/api/search.json?q=`.

**Comment by yipdw** [comment]
Neat, thanks for the review.  I've modified this PR:

- the endpoint is now `/api/search.json?q=`
- the endpoint now returns zero results when the query is omitted

**Comment by yipdw** [comment]
Maybe one last change: `/api/v1/search.json?q=`
Versioning the API in the path isn't that much more text or boilerplate, and it gives us a nice escape route for dealing with backwards-incompatible changes.

**Pull request merged**
